app/Http/Controllers/AuthenticationController.php
app/Http/Controllers/RegisteredUserController.php
app/Http/Requests/RegisterUserRequest.php
app/Models/Character.php
resources/js/store/store.js
routes/api.php

Registers a new user and creates default data to get a new user started with the app.

Allow new user to register (back-end) #17

---

app/Http/Controllers/TaskListController.php
app/Http/Resources/TaskListResource.php
app/Http/Resources/TaskResource.php
app/Models/Task.php
routes/api.php

Returns the TaskLists associated with a user, in a TaskListResource collection, each holding its respective tasks, in a TaskResourceCollection. Each task also carries its own sub task, and to prevent sub tasks from showing up double this filters out any subtasks in the main collection.

Show tasks in task lists to user (back-end) #30

---

app/Http/Controllers/TaskController.php
app/Http/Controllers/TaskListController.php
app/Http/Requests/StoreTaskRequest.php
app/Http/Resources/TaskListResource.php
app/Http/Resources/TaskResource.php
app/Models/Task.php
app/Rules/OwnerOf.php
app/Rules/OwnerOfTask.php
app/Rules/OwnerOfTaskList.php
app/Rules/ValidRepeatable.php
resources/css/app.css
resources/js/components/Navigation.vue
resources/js/components/NewTask.vue
resources/js/components/Task.vue
resources/js/components/TaskList.vue
resources/js/interceptors.js
resources/js/pages/Character.vue
resources/js/pages/Home.vue
resources/js/router/router.js
resources/js/store/store.js
routes/api.php
routes/web.php

Edited the task list in the database because it had a 'color' attribute that's not used and has no current implementation. Might come back in a future update, but for now it's unnecessary code.

Create a new task list (back-end) #21

---

app/Helpers/LevelHandler.php
app/Helpers/RewardHandler.php
app/Http/Controllers/CharacterController.php
app/Http/Controllers/TaskController.php
app/Http/Resources/CharacterResource.php
app/Http/Resources/FriendResource.php
app/Http/Resources/UserResource.php
app/Models/Character.php
app/Models/User.php
database/migrations/2021_07_05_083846_create_experience_points_table.php
database/seeders/DatabaseSeeder.php
database/seeders/ExperiencePointsSeeder.php
resources/js/app.js
resources/js/components/CharacterSummary.vue
resources/js/components/FriendsSummary.vue
resources/js/pages/Home.vue
resources/js/store/store.js
routes/api.php

Disregard branch name, the back-end part was already fixed in a previous branch, because it's sent the same way as the rest of the user data. There are icons in place to remove friend and to send them a message, though these things are not yet implemented, will be at a later date.

Create a place to see all friends (front-end) #53

---

app/Http/Controllers/UserController.php
app/Http/Resources/UserProfileResource.php
app/Http/Resources/UserResource.php
resources/js/components/AchievementsSummary.vue
resources/js/components/CharacterSummary.vue
resources/js/components/DeleteTaskListConfirm.vue
resources/js/components/EditTask.vue
resources/js/components/EditTaskList.vue
resources/js/components/FriendsSummary.vue
resources/js/components/Navigation.vue
resources/js/components/NewTask.vue
resources/js/components/NewTaskList.vue
resources/js/components/Task.vue
resources/js/interceptors.js
resources/js/pages/Home.vue
resources/js/pages/Login.vue
resources/js/pages/Profile.vue
resources/js/pages/Register.vue
resources/js/router/router.js
resources/js/store/modules/characterStore.js
resources/js/store/modules/taskListStore.js
resources/js/store/modules/taskStore.js
resources/js/store/modules/userStore.js
resources/js/store/store.js
routes/api.php

Combined both front and back-end because I made a mess of things. Shows a public profile, it's complete, but the design is awful. Will change later before release in a separate user story.

Create a public profile #50

---

app/Http/Controllers/AchievementController.php
app/Http/Controllers/UserController.php
app/Http/Resources/AchievementResource.php
app/Http/Resources/UserResource.php
app/Models/Achievement.php
app/Models/User.php
resources/js/components/Navigation.vue
resources/js/pages/Achievements.vue
resources/js/pages/Overview.vue
resources/js/router/router.js
resources/js/store/modules/achievementStore.js
resources/js/store/modules/adminStore.js
resources/js/store/store.js
routes/api.php

A lot of back-end stuff to make it fit. Also had to fiddle with the admin rights and checks, as this was needed.
Next time will have to add authentication/authorization for admin to actually perform actions.

Create a page to allow admins to manage achievements (front-end) #40

---

resources/js/app.js
resources/js/components/modals/ChangeRewardType.vue
resources/js/components/modals/EditAchievement.vue
resources/js/components/modals/EditCharacterName.vue
resources/js/components/modals/EditTask.vue
resources/js/components/modals/EditTaskList.vue

Made shallow copies of props

---

resources/js/components/Navigation.vue
resources/js/pages/Home.vue
resources/lang/en.json

Simple addition to home with buttons. Content to come later

---

resources/js/pages/Welcome.vue

Button added to modal

---

app/Http/Controllers/NotificationController.php
resources/assets/scss/app.scss
resources/js/components/small/NotificationBlock.vue
resources/js/store/modules/notificationStore.js
resources/lang/en.json
routes/api.php

Clicking it also gives a confirmation popup
Resolves: #205

Add a small button to delete a notification

---

app/Models/Task.php
resources/js/components/modals/NewTask.vue
resources/js/pages/Dashboard.vue

Eager loaded subtasks to reduce the needed queries every time you load all tasks
Also fixed a bug in subtasks that slipped under the radar. And fixed some console logs.
Resolves: #217

Eager loading subtasks

---

app/Http/Resources/BugReportResource.php
resources/js/constants/bugConstants.js
resources/js/pages/AdminBugPanel.vue
resources/js/store/modules/bugReportStore.js

The code works but had some console problems. Fixed those with some extra checks.
Also had eslint problems because the computed property wasn't allowed to mutate the property and it did. Moved the functionality to methods and calls it in computed, which somehow fixes the problem. Might have to look at it later, but for now it shuts up.
Oh and a small timestamp thing that looks better.

Fixed eslint and console problems

---

resources/js/pages/BugReport.vue
resources/js/store/modules/bugReportStore.js

everything should be fixed now uwu

imput fields clear/reset now on successfull submit

---

resources/js/components/Loading.vue
resources/js/pages/AdminDashboard.vue
resources/js/pages/Dashboard.vue
resources/js/pages/Friends.vue
resources/js/pages/Messages.vue
resources/js/pages/Notifications.vue
resources/js/pages/Overview.vue
resources/js/pages/Profile.vue
resources/js/store/modules/adminStore.js
resources/js/store/modules/friendStore.js
resources/js/store/modules/notificationStore.js
resources/js/store/modules/userStore.js
resources/js/store/store.js

Spinner to all important pages

---

app/Http/Controllers/AdminController.php
app/Http/Requests/StoreNewLevelRequest.php
resources/js/components/tabs/admin/Balancing.vue
resources/js/store/modules/adminStore.js
resources/lang/en.json
routes/api.php

Add new level to experience points and positioning

---

resources/js/components/bootstrap/BTab.vue
resources/js/components/bootstrap/BTabs.vue
resources/js/components/tabs/admin/Balancing.vue
resources/js/pages/AdminDashboard.vue
resources/js/pages/Settings.vue
resources/js/pages/Social.vue

Replaced Bootstrap with custom BTab. Pills need to be added as an option prop.
Resolves #305

Replaced BTabs

---

app/Http/Controllers/MessageController.php
resources/js/pages/Messages.vue
resources/lang/en.json

There was a bug on deleting messages, fixed that
And when there are no messages, there is a message saying so.
On load and resetConversation there is now a check to see if there are messages, if not, the emptyInbox variable is true and the 'no messages' message is shown.
Resolves #284

Delete message fix and message on no messages

---

resources/js/components/tabs/social/Groups.vue
resources/js/components/tabs/social/components/GroupDetails.vue

changed the valued to computed()
watch is no longer needed, since it is baked into computed()
(also reordered declarations of variables and functions)

a cleaner version, basically changed all values to computed()

---

app/Http/Controllers/NotificationController.php
resources/js/pages/Notifications.vue

Resolves #330 
fixed in in the js of the Notifications.vue component
other possible solutions:
- have a sortNotifications function in the store and call it
- have the notifications send from the back end in order

fixed the notification order

---

resources/js/components/tabs/social/components/SearchUser.vue

Resolves #326 
Added @submit.prevent to ensure the page doesn't reload on form submit.
Noticed a bug that I had double the envelopes when a user isn't connected.
Also added another check to make sure a user has requests before checking these requests. Same bug as previously with #303

Added submit prevent and request check

---

resources/assets/scss/app.scss
resources/js/components/small/Task.vue
resources/js/components/small/TaskList.vue
resources/js/pages/Dashboard.vue

Moved modals to their comps, removed emits

---

resources/js/pages/BugReport.vue
resources/js/pages/Login.vue
resources/js/pages/Register.vue
resources/js/pages/Welcome.vue
resources/js/pages/admin/components/CharExpGainTab.vue
resources/js/pages/admin/components/EditAchievement.vue
resources/js/pages/admin/components/EditBugReport.vue
resources/js/pages/admin/components/ExperiencePointsTab.vue
resources/js/pages/admin/components/NewAchievement.vue
resources/js/pages/admin/components/VillExpGainTab.vue
resources/js/pages/dashboard/components/DeleteTaskListConfirm.vue
resources/js/pages/dashboard/components/EditTask.vue
resources/js/pages/dashboard/components/EditTaskList.vue
resources/js/pages/dashboard/components/NewTask.vue
resources/js/pages/dashboard/components/NewTaskList.vue
resources/js/pages/messages/components/ReportUser.vue
resources/js/pages/messages/components/SendMessage.vue
resources/js/pages/notifications/Notifications.vue
resources/js/pages/settings/components/EditRewardObjectName.vue
resources/js/pages/settings/tabs/AccountSettings.vue
resources/js/pages/settings/tabs/ProfileSettings.vue
resources/js/pages/settings/tabs/RewardSettings.vue

All to CamelCase, mostly BaseFormError

---

app/Http/Controllers/UserController.php

Resolves #320 
Added visibility check, as all messages are already marked as invisible when a user gets blocked.

Added visibility check

---

app/Http/Controllers/MessageController.php
app/Http/Controllers/UserController.php
app/Http/Resources/BlockedUserResource.php
app/Models/BlockedUser.php
app/Models/User.php
deploy.sh
resources/js/icons.js
resources/js/pages/social/Social.vue
resources/js/pages/social/tabs/Blocklist.vue
resources/js/store/userStore.js
resources/lang/en.json
routes/api.php
vue.config.js

Resolves #250 
Also removed eager loading on Characters, as I don't think it's being used anymore.
Added a couple of things for deployment.

Blocklist functional

---

resources/js/components/global/Editable.vue

Resolves #352 
Will need extra validation once we start working on #290

Added basic validation on editable field.

---

app/Http/Resources/BugReportResource.php
app/Models/BugReport.php
resources/js/constants/bugConstants.js
resources/js/pages/admin/tabs/BugReportPanel.vue
resources/js/pages/messages/components/SendMessage.vue

Resolves #384 
Added a StrippedUserResource on user, rather than just a userId on user_id. 
The column now shows the username with a link to their profile.
The message now shows the name of the user.

Changed some names and added stripped user

---

app/Http/Controllers/NotificationController.php

404 optimise notification db calls

---

.eslintrc.json
resources/assets/scss/app.scss
resources/assets/scss/variants/baseVariables.scss
resources/js/icons.js
resources/js/pages/dashboard/components/Task.vue
resources/lang/i18n/task/en.json

Added icons and colours with tooltips

---

app/Http/Controllers/NotificationController.php

Moved the notifications get to reusable function

---

database/seeders/AchievementEarnedSeeder.php
database/seeders/AchievementSeeder.php
database/seeders/DatabaseSeeder.php

- Added an environment check so that the live version doesn't seed fake users etc, while still filling the necessary DB items such as achievements.
- Wrote out achievement names for the basic achievements currently in the game.

Achievement names in seeder and split by env

---

app/Http/Controllers/AdminController.php
app/Http/Resources/UserProfileResource.php
app/Http/Resources/UserSuspensionSummaryResource.php
app/Models/User.php
resources/js/pages/admin/components/SuspendUserModal.vue
resources/js/pages/profile/Profile.vue
resources/js/store/friendStore.js
resources/js/store/userStore.js
resources/lang/i18n/admin/en.json
resources/types/friend.d.ts
resources/types/user.d.ts

Ban through profile, see suspension on profile, timezone fix

---

app/Exceptions/GroupNotAuthorizedException.php
app/Http/Controllers/GroupsController.php
resources/js/App.vue
resources/js/interceptors.ts
resources/js/pages/social/components/GroupPage.vue

Added a singular exception to actions where you require admin privileges on groups and you don't have them. This makes it easier to edit the message/error code.
Resolves #443

Moved admin checks to one private function and added exception
